### ISSUE TITLE
Features list?

### ISSUE THREAD

**Issue by kdejaeger** [tlipinski/bitwig-novation-impulse#15]
Hi,

Nice project going on. Is the functionality of your work discussed somewhere on a forum? Or on a youtube video?

**Comment by tlipinski** [comment]
Hi! No, the functionality wasn't discussed anywhere. As a reference behavior I used Ableton + Novation Automap. Basic functionality is covered but it's still missing a few features I didn't manage to implement. Unfortunately I won't be able to work on them. Recently I've changed philosophy of making music which doesn't include Bitwig and Impulse anymore;)

**Comment by kdejaeger** [comment]
Owke :). What are you using now?

**Comment by tlipinski** [comment]
I realized that Bitwig is too complex for my needs. It might sound funny but now I'm using Caustic on my Android phone and PC:) I replaced Impulse with Arturia Minilab (25 keys) which doesn't take that much space in my room. It turned out that most of the time simple subtractive/fm synths and 606-like drums are all I need and making music on the way to work is also fun;)

**Comment by kdejaeger** [comment]
Waauw. Quite funny indeed. I'm always amased by the number of possibilities that exist.
